### ISSUE TITLE
Define and implement "Flex" context provider

### ISSUE THREAD

**Issue by AkihiroSuda** [containerbuilding/cbi#36]
maybe like

```yaml
apiVersion: cbi.containerbuilding.github.io/v1alpha1
kind: FlexContextProvider
metadata:
  name: foo
  labels:
    mediaType: application/tar+gzip
spec:
  template:
    spec:
      containers:
      - name: foo
         commands: ["cat", "a.tgz"]

---

apiVersion: cbi.containerbuilding.github.io/v1alpha1
kind: BuildJob
spec:
  context:
    kind: flex
    flex:
      providerRef:
        name: foo
      options:
        bar: baz 
   
```
