### ISSUE TITLE
ACB pod init error

### ISSUE THREAD

**Issue by yaron2** [containerbuilding/cbi#80]
Deployed the following YAML:
```
apiVersion: cbi.containerbuilding.github.io/v1alpha1
kind: BuildJob
metadata:
  name: ex-git-push
  annotations:
    cbi-acb/secret: my-acb
    cbi-acb/app-id: <removed details>
    cbi-acb/tenant: <removed details>
spec:
  registry:
    target: taacrdev.azurecr.io/samples/captainrogers
    push: true
  language:
    kind: Dockerfile
  context:
    kind: Git
    git:
      url: https://github.com/yaron2/captainrogers.git
  pluginSelector: plugin.name=acb
```

Describing a job pod outputs the following:
```
Init Containers:
  cbi-acb-init:
    Container ID:  docker://8f41fad8d617a9790d0c4cf88389bd0fb5721cdef0aba5ec51c33796f7d1a90a
    Image:         microsoft/azure-cli:latest
    Image ID:      docker-pullable://microsoft/azure-cli@sha256:6f74624ae7b62542d3babcaedba782b6851de677971d9dbbd03c5cecde392ff5
    Port:          <none>
    Host Port:     <none>
    Command:
      az
      login
      --service-principal
      --username
      <removed-details>
      --tenant
      <removed-details>
      --password
      /cbi-acbsecret/cert
    State:          Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Mon, 14 Jan 2019 17:39:05 -0800
      Finished:     Mon, 14 Jan 2019 17:39:06 -0800
    Ready:          False
    Restart Count:  0
    Environment:    <none>
```
