### ISSUE TITLE
Push to registry not working

### ISSUE THREAD

**Issue by badri** [containerbuilding/cbi#82]
After installing cbi in my cluster, I configured the following buildjob.

```
apiVersion: cbi.containerbuilding.github.io/v1alpha1
kind: BuildJob
metadata:
  name: django-s2i
spec:
  registry:
    target: registry.example.com/django/django-s2i:1.0
    push: true
  language:
    kind: S2I
    s2i:
      baseImage: lakshminp/django-alpine-s2i:1.0
  context:
    kind: Git
    git:
      url: https://gitlab.com/badri1/django-k8s-demo
```

The s2i build gets triggered but the image does not get pushed.

```
Build completed successfully
+ [ 1 = 1 ]
+ docker push registry.new-pine-ec5b.shapeblock.cloud/django/django-s2i:1.0
The push refers to repository [registry.example.com/django/django-s2i]
Get https://registry.example.com/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
```
My registry is configured with https and is currently unauthenticated.
